(()=>{
  const $=s=>document.querySelector(s),urlKey='leave-now-worker-url',tokenKey='leave-now-token',subKey='leave-now-sub-id';
  const message=s=>{const el=$('#alertSetup');if(el)el.textContent=s};
  const base=()=>localStorage.getItem(urlKey)||'',token=()=>localStorage.getItem(tokenKey)||'';
  async function call(path,body,method){const res=await fetch(base().replace(/\/$/,'')+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error||'Push service request failed.');return data}
  async function subscribe(){if(!base()||!token())throw Error('Connect the free Cloudflare push service first.');if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw Error('Install this app in a browser that supports phone notifications.');let permission=Notification.permission;if(permission!=='granted')permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Allow notifications in phone settings.');const health=await fetch(base().replace(/\/$/,'')+'/health'),info=await health.json();if(!health.ok||!info.vapidPublicKey)throw Error('Worker is missing its push configuration.');const reg=await navigator.serviceWorker.register('./sw.js'),ready=await navigator.serviceWorker.ready;let sub=await ready.pushManager.getSubscription();if(!sub)sub=await ready.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(info.vapidPublicKey)});const r=await call('/v1/push',sub.toJSON());localStorage.setItem(subKey,r.subscriptionId);return true}
  function decode(s){const raw=atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
  const connect=$('#connectWorker');if(connect)connect.onclick=async()=>{const u=$('#workerUrl').value.trim().replace(/\/$/,''),t=$('#appToken').value.trim();if(!u.startsWith('https://')||!t)return message('Enter the Cloudflare Worker URL and private app token.');try{const r=await fetch(u+'/health'),d=await r.json();if(!r.ok||!d.vapidPublicKey)throw Error('Worker is not deployed or push is not configured.');localStorage.setItem(urlKey,u);localStorage.setItem(tokenKey,t);message('Push service connected. Tap Enable notifications, then Schedule my alerts.')}catch(e){message(e.message)}};
  const enable=$('#enableNotifications');if(enable)enable.onclick=async()=>{try{if(!base()){if(!('Notification'in window))throw Error('This browser does not support notifications.');const p=await Notification.requestPermission();if(p!=='granted')throw Error('Allow phone notifications.');await navigator.serviceWorker?.register('./sw.js');message('Local notifications enabled. For reminders while the app is closed, connect the free Cloudflare push service.');return}await subscribe();message('Phone notifications enabled. Tap Schedule my alerts to sync the 30/15/now reminders.')}catch(e){message(e.message)}};
  const schedule=$('#scheduleAlerts');if(schedule){const previous=schedule.onclick;schedule.onclick=async function(e){if(base()&&token()&&!localStorage.getItem(subKey)){try{await subscribe()}catch(err){message(err.message);return}}if(previous)await previous.call(this,e)}};
  const clear=$('#clearHistory');if(clear)clear.onclick=async()=>{if(!confirm('Clear all saved routes, profile and trip history from this phone?'))return;try{if(base()&&token())await call('/v1/schedule/main-commute',null,'DELETE')}catch{}for(const k of Object.keys(localStorage))if(k.startsWith('leave-now-'))localStorage.removeItem(k);location.reload()};
  const disconnect=$('#disconnectWorker');if(disconnect)disconnect.onclick=async()=>{try{if(base()&&token())await call('/v1/schedule/main-commute',null,'DELETE')}catch{}for(const k of [urlKey,tokenKey,subKey])localStorage.removeItem(k);$('#workerUrl').value='';$('#appToken').value='';message('Push disconnected. Existing local history remains on this phone.')};
  const query=new URLSearchParams(location.search);if(query.get('push')==='1'){const title=({30:'Leave in 30 minutes',15:'Leave in 15 minutes',0:'Leave now'})[query.get('kind')]||'Commute reminder',eta=query.get('eta'),safe=query.get('conservative'),arrival=query.get('arrival'),confidence=query.get('confidence'),route=query.get('route');message(`${title}${route?' · '+route:''}. ETA ${eta||'—'} min; allow ~${safe||'—'} min; arrive by ${arrival||'—'} · ${confidence||'—'} confidence.`);history.replaceState({},'',location.pathname)}
})();
