(()=>{'use strict';
const KEY='leave-now-tomtom-key-v1',q=s=>document.querySelector(s);let map=null,base=null,flow=null,routeLine=null,startMarker=null,endMarker=null,requestId=0;
const settings=document.createElement('details');settings.className='card';settings.id='tomtomSettings';settings.innerHTML='<summary style="font-weight:700;cursor:pointer">TomTom map setup</summary><p class="sub">Paste your TomTom API key. It stays in this browser on this phone and is not written into app files.</p><label><span class="label">TomTom API key</span><input type="password" id="tomtomKey" class="field" autocomplete="off" placeholder="Paste your TomTom key"></label><div class="row" style="margin-top:10px"><button class="btn soft" id="saveTomtomKey">Save on this phone</button><button class="btn ghost" id="removeTomtomKey">Remove key</button></div><div id="tomtomKeyStatus" class="small" style="margin-top:8px"></div><p class="small">In TomTom, enable Map Display, Traffic Flow, Search, and Routing APIs for this key. Browser keys are visible to users, so restrict the key to those APIs and your GitHub Pages website.</p>';
const target=q('#mapsSetup');if(target)target.before(settings);q('#tomtomKey').value=localStorage.getItem(KEY)||'';
function setStatus(text){q('#tomtomKeyStatus').textContent=text}
setStatus(localStorage.getItem(KEY)?'Key saved on this phone.':'No key saved on this phone.');
q('#saveTomtomKey').onclick=()=>{const k=q('#tomtomKey').value.trim();if(!k)return setStatus('Paste your API key first.');localStorage.setItem(KEY,k);setStatus('TomTom key saved on this phone.');window.updateTomTomMap?.()};
q('#removeTomtomKey').onclick=()=>{localStorage.removeItem(KEY);q('#tomtomKey').value='';if(map){map.remove();map=null}setStatus('TomTom key removed from this phone.');window.updateTomTomMap?.()};
function setupMap(key){if(map)return;const el=q('#routeMapFrame');if(!el||!window.L)throw Error('Map component did not load. Check your internet connection and reload the app.');map=L.map(el,{zoomControl:true,scrollWheelZoom:false}).setView([18.5204,73.8567],12);base=L.tileLayer('https://{s}.api.tomtom.com/map/1/tile/basic/main/{z}/{x}/{y}.png?key='+encodeURIComponent(key),{subdomains:'abcd',maxZoom:20,tileSize:256,attribution:'© TomTom'}).addTo(map);flow=L.tileLayer('https://api.tomtom.com/traffic/map/4/tile/flow/relative0/{z}/{x}/{y}.png?key='+encodeURIComponent(key)+'&tileSize=256',{maxZoom:20,tileSize:256,opacity:.82,attribution:'Traffic © TomTom'}).addTo(map);map.on('tileerror',()=>{const state=q('#mapState');if(state){state.classList.remove('hidden');state.querySelector('strong').textContent='TomTom could not load map tiles';state.querySelector('p').textContent='Check that Map Display and Traffic Flow are enabled for this API key.'}})}
function applyLiveEstimate(route,mode){const seconds=route?.summary?.travelTimeInSeconds,routeId=q('#routeSelect')?.value;if(!Number.isFinite(seconds)||!routeId)return;window.dispatchEvent(new CustomEvent('leave-now-live-route',{detail:{minutes:Math.max(1,Math.ceil(seconds/60)),mode:mode==='motorcycle'?'bike':'car',routeId,at:Date.now()}}))}
async function geocode(name,key){const url='https://api.tomtom.com/search/2/geocode/'+encodeURIComponent(name+', Pune, India')+'.json?key='+encodeURIComponent(key)+'&countrySet=IN&limit=1';const r=await fetch(url);if(!r.ok)throw Error('TomTom could not look up this place. Check that Search API is enabled and use a specific Pune area.');const p=(await r.json()).results?.[0]?.position;if(!p)throw Error('Could not find this place in Pune. Try a specific locality such as Baner or Hinjawadi.');return p}
async function update(){const key=localStorage.getItem(KEY),origin=q('#origin')?.value.trim(),destination=q('#destination')?.value.trim(),state=q('#mapState'),mapVisible=!!q('#screen-map')&&!q('#screen-map').hidden;if(!origin||!destination){if(mapVisible&&state){state.classList.remove('hidden');state.querySelector('strong').textContent='Choose a saved route';state.querySelector('p').textContent='Save a route on the Plan tab to preview it here.'}return}if(!key){if(mapVisible&&state){state.classList.remove('hidden');state.querySelector('strong').textContent='Add your TomTom API key';state.querySelector('p').textContent='Open Settings → TomTom map setup, save your key, then return here.'}return}const id=++requestId;try{if(mapVisible){setupMap(key);state.classList.remove('hidden');state.querySelector('strong').textContent='Loading your TomTom route…';state.querySelector('p').textContent='Finding the route and live traffic around Pune.';map.invalidateSize()}const [a,b]=await Promise.all([geocode(origin,key),geocode(destination,key)]);if(id!==requestId)return;const mode=q('[data-mode].active')?.dataset.mode==='bike'?'motorcycle':'car';const loc=[a.lat+','+a.lon,b.lat+','+b.lon].join(':');const url='https://api.tomtom.com/routing/1/calculateRoute/'+loc+'/json?key='+encodeURIComponent(key)+'&traffic=true&travelMode='+mode+'&computeTravelTimeFor=all';const response=await fetch(url);if(!response.ok)throw Error('TomTom routing failed. Check that Routing API is enabled for this key.');const data=await response.json(),route=data.routes?.[0],points=(route?.legs||[]).flatMap(x=>x.points||[]).map(x=>[x.latitude,x.longitude]);if(!route)throw Error('TomTom returned no route. Check the saved locations.');if(id!==requestId)return;applyLiveEstimate(route,mode);if(mapVisible){if(!points.length)throw Error('TomTom returned no route geometry.');if(routeLine)map.removeLayer(routeLine);if(startMarker)map.removeLayer(startMarker);if(endMarker)map.removeLayer(endMarker);routeLine=L.polyline(points,{color:'#167a58',weight:6,opacity:.92}).addTo(map);startMarker=L.circleMarker([a.lat,a.lon],{radius:8,color:'#fff',weight:3,fillColor:'#167a58',fillOpacity:1}).addTo(map).bindPopup('Starting point');endMarker=L.circleMarker([b.lat,b.lon],{radius:8,color:'#fff',weight:3,fillColor:'#d94b45',fillOpacity:1}).addTo(map).bindPopup('Destination');map.fitBounds(routeLine.getBounds().pad(.12),{maxZoom:14});state.classList.add('hidden');map.invalidateSize()}}catch(e){if(id!==requestId)return;if(mapVisible&&state){state.classList.remove('hidden');state.querySelector('strong').textContent='Could not load the TomTom route';state.querySelector('p').textContent=e.message||'Please check your API key and try again.'}}}
window.addEventListener('leave-now-tomtom-map-update',update);q('#saveRoute')?.addEventListener('click',()=>setTimeout(update,500));q('#routeSelect')?.addEventListener('change',()=>setTimeout(update,150));q('#saveArrivalTime')?.addEventListener('click',()=>setTimeout(update,150));q('#arrivalTime')?.addEventListener('change',()=>setTimeout(update,150));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setTimeout(update,150)));q('#tab-map')?.addEventListener('click',()=>setTimeout(update,150));window.updateTomTomMap=update;setTimeout(update,0);
})();
