(()=>{
  const main=document.querySelector('main.app');if(!main)return;
  // Restore and wire the theme control; the CSS palettes already exist in index.html.
  const themeKey='leave-now-theme-v1',root=document.documentElement,themeButton=document.querySelector('#themeToggle');
  function applyTheme(theme){const dark=theme==='dark';root.classList.toggle('dark-theme',dark);root.classList.toggle('light-theme',!dark);if(themeButton){themeButton.textContent=dark?'☀':'☾';themeButton.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');themeButton.title=dark?'Switch to light theme':'Switch to dark theme'}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#0c1714':'#f4f6f2'}
  let savedTheme='light';try{savedTheme=localStorage.getItem(themeKey)||'light'}catch{}applyTheme(savedTheme);
  themeButton?.addEventListener('click',()=>{savedTheme=root.classList.contains('dark-theme')?'light':'dark';applyTheme(savedTheme);try{localStorage.setItem(themeKey,savedTheme)}catch{}});
  const greeting=main.querySelector('.greeting');
  const cards=[...main.querySelectorAll(':scope > section.card')],details=[...main.querySelectorAll(':scope > details.card')];
  const make=(id,title,hint)=>{const section=document.createElement('section');section.className='screen';section.id=id;section.innerHTML=`<h1 class="screen-title">${title}</h1><p class="screen-hint">${hint}</p>`;main.insertBefore(section,main.querySelector('.footer'));return section};
  const plan=make('screen-plan','Your commute, handled','Set your arrival once. Your plan and reminders learn from your commute history.');
  const map=make('screen-map','Route map','See your saved route inside Leave Now.');
  const journey=make('screen-journey','Journey','Track a trip once. Leave Now learns how long your commute really takes.');
  const insights=make('screen-insights','Your patterns','See when you travel best and how often you reach your target.');
  const settings=make('screen-settings','Preferences','Personalize your commute and notification setup.');
  if(greeting){plan.append(greeting);greeting.classList.add('landing-hero');const copy=greeting.querySelector('p');if(copy)copy.textContent='A clear departure plan, shaped around your arrival time and current traffic.';const cta=document.createElement('button');cta.type='button';cta.className='landing-cta';cta.id='landingCta';greeting.append(cta);const origin=document.querySelector('#origin'),destination=document.querySelector('#destination'),routeCard=main.querySelector('#routeCard');const refresh=()=>{const saved=!!(origin?.value.trim()&&destination?.value.trim());cta.textContent=saved?'Refresh my commute plan':'Set up my commute';cta.setAttribute('aria-label',saved?'Refresh current route and commute recommendation':'Set up your starting point and destination')};cta.onclick=()=>{if(!origin?.value.trim()||!destination?.value.trim()){routeCard?.scrollIntoView({behavior:'smooth',block:'center'});origin?.focus();return}window.dispatchEvent(new Event('leave-now-tomtom-map-update'));document.querySelector('#departAt')?.scrollIntoView({behavior:'smooth',block:'center'})};['#saveRoute','#routeSelect'].forEach(sel=>document.querySelector(sel)?.addEventListener('click',()=>setTimeout(refresh,250)));document.querySelector('#routeSelect')?.addEventListener('change',()=>setTimeout(refresh,20));refresh()}
  [cards[0],cards[1],cards[2],cards[3]].filter(Boolean).forEach(x=>plan.append(x));
  const outlook=cards[3];if(outlook){const tabs=outlook.querySelector('.tabs'),patterns=outlook.querySelector('#panelPatterns'),week=outlook.querySelector('#panelWeek');tabs?.querySelector('[data-view="today"]')?.remove();if(tabs)insights.append(tabs);if(patterns){insights.append(patterns);patterns.classList.remove('hidden')}if(week)insights.append(week);if(tabs){tabs.setAttribute('role','tablist');tabs.querySelectorAll('.tab').forEach((b,i)=>{b.setAttribute('role','tab');b.id='insight-tab-'+b.dataset.view;b.setAttribute('aria-controls','panel'+b.dataset.view[0].toUpperCase()+b.dataset.view.slice(1));b.setAttribute('aria-selected',String(i===0));b.tabIndex=i===0?0:-1});[patterns,week].filter(Boolean).forEach(p=>p.setAttribute('role','tabpanel'));tabs.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{tabs.querySelectorAll('.tab').forEach(x=>{const active=x===b;x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1});outlook.querySelector('#panelToday')?.classList.remove('hidden')}))}}
  [cards[4],cards[5],cards[6],cards[7]].filter(Boolean).forEach(x=>journey.append(x));if(cards[8])insights.append(cards[8]);details.forEach(x=>settings.append(x));
  const routeCard=cards[0];
  if(routeCard){
    const heading=routeCard.querySelector('.cardhead'),save=routeCard.querySelector('#saveRoute'),mapsButton=routeCard.querySelector('#mapsBtn');
    const preview=document.createElement('div');preview.className='route-preview';preview.innerHTML='<span class="route-dots" aria-hidden="true">●<span>⋮</span>●</span><span class="route-copy"><span class="route-caption">SAVED ROUTE</span><span id="routePreviewText"></span></span><button type="button" class="btn ghost route-edit" id="editRouteBtn">Edit</button>';heading.insertAdjacentElement('afterend',preview);let editing=true;
    const paint=()=>{const origin=document.querySelector('#origin').value.trim(),dest=document.querySelector('#destination').value.trim(),saved=!!(origin&&dest);document.querySelector('#routePreviewText').textContent=saved?origin+' → '+dest:'Add your home and office';routeCard.classList.toggle('route-saved',saved&&!editing);if(!saved)routeCard.classList.remove('route-saved')};
    document.querySelector('#editRouteBtn').onclick=()=>{editing=true;paint();document.querySelector('#origin').focus()};
    ['#routeName','#origin','#destination'].forEach(sel=>document.querySelector(sel).addEventListener('input',()=>{editing=true;paint()}));save?.addEventListener('click',()=>{editing=false;paint()});document.querySelector('#newRouteBtn')?.addEventListener('click',()=>{editing=true;paint()});document.querySelector('#routeSelect')?.addEventListener('change',()=>{editing=false;setTimeout(paint,0)});paint();
  }
  map.innerHTML='<h1 class="screen-title">Route map</h1><p class="screen-hint">Your route and live traffic, inside Leave Now.</p><section class="card map-card"><div class="map-info"><span><strong id="mapRouteLabel">No route selected</strong><br>TomTom map · live traffic</span><span class="chip" id="mapModeLabel">CAR</span></div><div id="mapState" class="map-state"><strong>TomTom map ready</strong><p>Save a route and add your TomTom API key in Settings to view the map and traffic.</p></div><div id="routeMapFrame" class="map-frame" role="application" aria-label="TomTom map with live traffic"></div><div class="map-actions"><a class="btn primary" id="mapGoogleLink" href="https://maps.google.com/" target="_blank" rel="noopener">Open Google Maps ↗</a><a class="btn soft hidden" id="mapOpenMaps" href="https://www.openstreetmap.org/" target="_blank" rel="noopener">Open OpenStreetMap directions ↗</a></div><p class="small">Colored roads show live traffic: green is flowing, yellow or orange is slower, and red is heavy congestion. Traffic can change while you travel.</p></section>';  const nav=document.createElement('nav');nav.className='bottom-nav';nav.setAttribute('aria-label','Main navigation');nav.setAttribute('role','tablist');nav.innerHTML=[['plan','⌂','Plan'],['map','⌖','Map'],['journey','➜','Journey'],['insights','▥','Insights'],['settings','⚙','Settings']].map(([id,icon,label])=>`<button type="button" class="nav-item" role="tab" id="tab-${id}" data-screen="screen-${id}" aria-controls="screen-${id}" aria-label="${label}"><span class="nav-icon" aria-hidden="true">${icon}</span><span>${label}</span></button>`).join('');main.append(nav);
  const screens=[plan,map,journey,insights,settings],buttons=[...nav.querySelectorAll('.nav-item')];screens.forEach(s=>{s.setAttribute('role','tabpanel');const b=buttons.find(x=>x.dataset.screen===s.id);if(b)s.setAttribute('aria-labelledby',b.id)});
  function show(id){const target=screens.find(s=>s.id===id);if(!target)return;screens.forEach(s=>{const active=s===target;s.classList.toggle('active',active);s.hidden=!active});buttons.forEach(b=>{const active=b.dataset.screen===id;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'smooth'});try{localStorage.setItem('leave-now-last-tab',id)}catch{}if(id==='screen-map'){try{updateMap()}catch(error){state.querySelector('strong').textContent='Map is temporarily unavailable';state.querySelector('p').textContent='Your saved commute is still available on the Plan tab.'}}}
  nav.addEventListener('click',e=>{const button=e.target.closest('.nav-item');if(!button)return;e.preventDefault();show(button.dataset.screen)},true);
  buttons.forEach((b,i)=>{b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[n].focus();show(buttons[n].dataset.screen)}});
  document.querySelector('#profileBtn')?.addEventListener('click',()=>{show('screen-settings');document.querySelector('details').open=true});
  const state=document.querySelector('#mapState'),googleLink=document.querySelector('#mapGoogleLink');
  function updateMap(){const origin=document.querySelector('#origin')?.value.trim(),destination=document.querySelector('#destination')?.value.trim(),mode=document.querySelector('[data-mode].active')?.dataset.mode||'car',routeName=document.querySelector('#routeName')?.value.trim();document.querySelector('#mapRouteLabel').textContent=origin&&destination?(routeName||origin+' → '+destination):'No route selected';document.querySelector('#mapModeLabel').textContent=mode.toUpperCase();if(origin&&destination){const q=new URLSearchParams({api:'1',origin,destination,travelmode:mode==='bike'?'two-wheeler':'driving'});googleLink.href='https://www.google.com/maps/dir/?'+q.toString();googleLink.classList.remove('hidden');state.querySelector('strong').textContent='Loading your TomTom map…';state.querySelector('p').textContent='Getting your saved route and current traffic.'}else{googleLink.classList.add('hidden');state.querySelector('strong').textContent='Choose a saved route';state.querySelector('p').textContent='Save a route on the Plan tab and add your TomTom API key in Settings.'}window.dispatchEvent(new Event('leave-now-tomtom-map-update'))}
  window.updateTomTomMap=updateMap;
  document.querySelector('#saveRoute')?.addEventListener('click',()=>setTimeout(updateMap,300));document.querySelector('#routeSelect')?.addEventListener('change',()=>setTimeout(updateMap,0));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>updateMap()));
  let initial='screen-plan';try{const saved=localStorage.getItem('leave-now-last-tab');if(screens.some(s=>s.id===saved))initial=saved}catch{}show(initial);
})();
